### PR TITLE
add python eda part

### PR DESCRIPTION
**Pull request by xiangwxt**
Hi team, I update the python eda part. Please help review the pr. Thanks!

### CODE REVIEW

**Comment by NikitaShymberg** [comment]
This is awesome! I see that you've gone above and beyond the basic EDA! I have a couple of comments:

- I see that there is some R EDA as well (as well as the arrow stuff), how will this combine with @kphaterp 's work?
- I think it's better to have all the `import` statements at the very top of the notebook
- I notice that your variable names are `df_0`, `df_1`, and `df_2`. Could you make these more descriptive please?
- I see that you looked at `value_counts()` for all the 3 dfs but they all have the same counts because it's the same data - was this just to compare runtimes? If so, maybe it's a good idea to add a couple of sentences summarizing this!

Again, great job!

**Comment by voremargot** [comment]
I love the analysis you did!  I agree with Nikita that the variable names could be more descriptive so I can follow the EDA better.  Do we need to add in any EDA plots for python? It is unclear from the milestone but if so I am happy to make a simple map that shows the locations of the weather stations we are working with! Thoughts @xiangwxt @NikitaShymberg @kphaterp?

**Comment by NikitaShymberg** [comment]
Maps are fun! I think that would be a good visualization. Maybe let's ask Gittu or a TA to see what their expectations are?

**Comment by kphaterp** [comment]
A map would be great as long as its not too much of a hassle for Thea! I checked the Milestone instructions and under 'Specific Expectations for this Milestone', it looks like the instructions are nudging us to create basic visualizations for the EDA. I could be wrong though

**Comment by xiangwxt** [comment]
I think the purpose of the EDA part is to compare the run time, so I'm trying to find the simple eda that can help compare run time among 4 methods. It's always better to have plots in EDA but here I think one general should be enough as I cannot compare them within all 4 methods. Please correct me if I'm wrong. Thanks for those suggestions, I will try to revise it accordingly.

**Comment by voremargot** [comment]
I agree that the main point is definitely comparing the run times of different methods and you nailed that.  I can take or leave a plot myself so if we want to try a plot with one method I am happy to implement it!

**Comment by xiangwxt** [comment]
Hi team, thank you very much for all those comments. I have revised them accordingly and tried to aline the format with the R part. Please help review the new version. Thanks a lot!

**Review by kphaterp — APPROVED** [review]

**Pull request merged**
